# Generated by Django 3.2.9 on 2021-11-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_rename_categoria_id_contato_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
